name: Check Code Quality On Push

on:
  push:
    branches:
      - master
      - develop
      - release-*
  pull_request:
    branches:
      - develop

jobs:
  call_codequality:
    uses: ./.github/workflows/codequality.yml