name: Test Sphinx Build

on:
  push:
    branches:
      - tox

jobs:
  docs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python ${{ matrix.python }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install -e ".[dev]"
      - name: Install Pandoc
        run:
          sudo apt-get install pandoc
#      - name: Install Tox and Dependencies
          ##        run: |
          ##          pip install tox
          ##          echo 'Smoke test successful through tox intallation.'
          ##      - name: Run Tox
          ##        run: |
        ##            echo 'About to run tox'
        ##            tox -e docs
#      - name: Install wheel
#        run:
#          pip install wheel
#      - name: Install sphinx
#        run:
#          sudo apt-get install python-sphinx
#      - name: Install sphinx dependencies
#        run:
#          pip install sphinx_rtd_theme sphinxcontrib-napoleon nbsphinx
      - name: Build HTML
        run:
          sphinx-build -W -b html -d docs/doctrees docs/source docs/build/html