name: Cross-Platform Smoke Test

on:
  push:
    branches:
      - tox

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
#        with:
#          python-version: ${{ matrix.python }}
      - name: Install Pandoc
        uses: docker://pandoc/core:2.9
#      - name: Install Tox and Dependencies
          ##        run: |
          ##          pip install tox
          ##          echo 'Smoke test successful through tox intallation.'
          ##      - name: Run Tox
          ##        run: |
        ##            echo 'About to run tox'
        ##            tox -e docs
      - name: Build HTML
        run: |
          pip install sphinx sphinx_rtd_theme sphinxcontrib-napoleon nbsphinx
          sphinx-build -W -b html -d docs/doctrees docs/source docs/build/html