name: Tox Cross-Platform

on:
  push:
    branches:
      - master
      - develop
      - tox

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        python: [3.6, 3.7, 3.8]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
      - name: Install Tox and Dependencies
        run: pip install tox
      - name: Run Tox
        run: tox -e py