name: Tox Cross-Platform

on:
  push:
    branches:
      - master
      - develop
      - release-*
  pull_request:
    branches:
      - develop

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        python: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Install Tox and Dependencies
        run: pip install tox
      - name: Run Tox
        run: tox -e py